Fix a bad format directive.
Downstream we see:
```
timeout_test.go:113: Error waiting for TaskRun pipeline-run-timeout-pjyoxlbt-foo to be running: %!s(<nil>)
```

We need to capture `err` to print it!

This follows the same pattern as the rest of the file.