Update xerrors dependency
Our vendored xerrors causes build failures when using go 1.13:

```bash
λ go build -o /dev/null ./cmd/controller/
vendor/golang.org/x/xerrors/adaptor_go1_13.go:16:14: undefined: errors.Frame
vendor/golang.org/x/xerrors/format_go1_13.go:12:18: undefined: errors.Formatter
```

errors.Frame and errors.Formatter were removed from 1.13 and xerrors was
updated here:
https://github.com/golang/xerrors/commit/a985d3407aa71f30cf86696ee0a2f409709f22e1