Updating to include Tekton installtion
Without this, students trying this tutorial will get:
error: unable to recognize "task.yaml": no matches for kind "Task" in version "tekton.dev/v1alpha1"