Compress Runs' data before adding to annotations
When `embedded-status` is set to `both` or `full`, then TaskRun and
PipelineRun payload JSON is added to annotations to facilitate
conversion. This JSON payload is occasionally too large to fit into
annotations and the maximum size limit of annotations (256 kB, combined
limit for all annotations) is exceeded leading to errors while fetching
Tekton workloads.

Example:
```
$ tkn pr ls
Failed to list objects from pipelines-ci namespace
Error: failed to list PipelineRuns from namespace pipelines-ci: conversion webhook for tekton.dev/v1beta1, Kind=PipelineRun returned invalid metadata: metadata.annotation: Too long: must have at most 262144 bytes
```

This commit mitigates this in 2 ways:
- The JSON payload is compressed before adding to the annotations. This
  helps in reducing the size footprint of the annotations quite a bit.
  The data is further encoded after compression so as to sanitize the
  compressed data which is in binary.
- Once the annotations are added, the size is validated and an error is
  returned if the annotions size limit is exceeded.

Co-authored-by: Vincent Demeester <vdemeest@redhat.com>